name: matplotlib-tutorial 
channels:
  - conda-forge
dependencies:
  # Analysis packages
  - numpy
  - pandas
  - xarray
  - scipy
  # Visualization packages
  - matplotlib
  - basemap
  - cartopy
  - cmocean
  # I/O
  - netcdf4
  - nc-time-axis
